PROFILE_TYPE_VENDOR = "vendor"
PROFILE_TYPE_CUSTOMER = 'customer'
PROFILE_TYPE_ADMIN = 'admin'

PROFILE_TYPE = (
    (PROFILE_TYPE_VENDOR, "vendor"),
    (PROFILE_TYPE_CUSTOMER, "customer"),
    (PROFILE_TYPE_ADMIN, "admin")
)

COUPON_TYPE_FLAT = "flat"
COUPON_TYPE_PERCENT = 'percent'

COUPON_TYPE = (
    (COUPON_TYPE_FLAT, "Flat"),
    (COUPON_TYPE_PERCENT, "Percent")
)

PRODUCT_TYPE_PRODUCT = "product"
PRODUCT_TYPE_SERVICE = 'service'

PRODUCT_TYPES = (
    (PRODUCT_TYPE_PRODUCT, "Product"),
    (PRODUCT_TYPE_SERVICE, "Service")
)

ENQUIRY_STATUS_APPROVED = "approved"
ENQUIRY_STATUS_PENDING = 'pending'

ENQUIRY_STATUS = (
    (ENQUIRY_STATUS_APPROVED, "Approved"),
    (ENQUIRY_STATUS_PENDING, "Pending")
)

ORDER_STATUS_COMPLETED = "completed"
ORDER_STATUS_UPCOMING = 'upcoming'
ORDER_STATUS_CANCELLED = 'cancelled'

ORDER_STATUS = (
    (ORDER_STATUS_COMPLETED, "Completed"),
    (ORDER_STATUS_UPCOMING, "Upcoming"),
    (ORDER_STATUS_CANCELLED, "Cancelled")
)

COUPON_STATE_ACTIVE = 'active'
COUPON_STATE_DISABLED = 'disabled'

COUPON_STATES = (
    (COUPON_STATE_ACTIVE, "Active"),
    (COUPON_STATE_DISABLED, "Disabled")
)

PAYMENT_STATUS_SUCCESSFULL = "successful"
PAYMENT_STATUS_PENDING = 'pending'

PAYMENT_STATUS = (
    (PAYMENT_STATUS_SUCCESSFULL, "Successful"),
    (PAYMENT_STATUS_PENDING, "Pending")
)

CATEGORY_TYPE_HAIRCUT = 'haircut'
CATEGORY_TYPE_SPA = 'spa'
CATEGORY_TYPE_MASSAGE = 'massage'
CATEGORY_TYPE_OTHERS = 'others'

CATEGORY_TYPES = (
    (CATEGORY_TYPE_HAIRCUT, "Haircut"),
    (CATEGORY_TYPE_SPA, "Spa"),
    (CATEGORY_TYPE_MASSAGE, "Massage"),
    (CATEGORY_TYPE_OTHERS, "Others"),
)