# Generated by Django 3.0.5 on 2021-03-08 20:02

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('validity', djongo.models.fields.JSONField()),
                ('couponDetail', djongo.models.fields.JSONField()),
                ('vendorId', models.TextField()),
                ('category', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=1024)),
                ('count', models.IntegerField(default=0)),
                ('maxCount', models.IntegerField(null=True)),
                ('minAmount', models.IntegerField(null=True)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'coupons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('profileId', models.TextField()),
                ('productId', models.TextField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=1024)),
                ('quantity', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'enquiries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('productId', models.TextField()),
                ('vendorId', models.TextField()),
                ('customerId', models.TextField()),
                ('customerName', models.TextField()),
                ('contact', djongo.models.fields.JSONField()),
                ('payment', djongo.models.fields.JSONField()),
                ('time', djongo.models.fields.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('orderStatus', models.CharField(choices=[('completed', 'Completed'), ('upcoming', 'Upcoming'), ('cancelled', 'Cancelled')], default='upcoming', max_length=1024)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('sales', models.IntegerField(default=0)),
                ('timings', djongo.models.fields.JSONField()),
                ('productAvailability', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=5)),
                ('productType', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=1024)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profileType', models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], default='flat', max_length=1024)),
                ('vendorDescription', models.TextField(null=True)),
                ('contact', djongo.models.fields.JSONField()),
                ('address', djongo.models.fields.JSONField()),
                ('privacySetting', djongo.models.fields.JSONField()),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=10)),
                ('image', models.TextField()),
                ('lastAppActivity', models.DateTimeField(null=True)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_admin_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending')], default='pending', max_length=1024)),
                ('amount', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
    ]
